USE tifosi;

-- Insertion des marques
INSERT INTO marque (nom) VALUES ('Coca-cola');
INSERT INTO marque (nom) VALUES ('Cristalline');
INSERT INTO marque (nom) VALUES ('Monster');
INSERT INTO marque (nom) VALUES ('Pepsico');

-- Insertion des boissons
INSERT INTO boisson (nom, id_marque) VALUES ('Coca-cola zéro', (SELECT id_marque FROM marque WHERE nom = 'Coca-cola'));
INSERT INTO boisson (nom, id_marque) VALUES ('Coca-cola original', (SELECT id_marque FROM marque WHERE nom = 'Coca-cola'));
INSERT INTO boisson (nom, id_marque) VALUES ('Fanta citron', (SELECT id_marque FROM marque WHERE nom = 'Coca-cola'));
INSERT INTO boisson (nom, id_marque) VALUES ('Fanta orange', (SELECT id_marque FROM marque WHERE nom = 'Coca-cola'));
INSERT INTO boisson (nom, id_marque) VALUES ('Capri-sun', (SELECT id_marque FROM marque WHERE nom = 'Coca-cola'));
INSERT INTO boisson (nom, id_marque) VALUES ('Pepsi', (SELECT id_marque FROM marque WHERE nom = 'Pepsico'));
INSERT INTO boisson (nom, id_marque) VALUES ('Pepsi Max Zéro', (SELECT id_marque FROM marque WHERE nom = 'Pepsico'));
INSERT INTO boisson (nom, id_marque) VALUES ('Lipton zéro citron', (SELECT id_marque FROM marque WHERE nom = 'Pepsico'));
INSERT INTO boisson (nom, id_marque) VALUES ('Lipton Peach', (SELECT id_marque FROM marque WHERE nom = 'Pepsico'));
INSERT INTO boisson (nom, id_marque) VALUES ('Monster energy ultra gold', (SELECT id_marque FROM marque WHERE nom = 'Monster'));
INSERT INTO boisson (nom, id_marque) VALUES ('Monster energy ultra blue', (SELECT id_marque FROM marque WHERE nom = 'Monster'));
INSERT INTO boisson (nom, id_marque) VALUES ('Eau de source ', (SELECT id_marque FROM marque WHERE nom = 'Cristalline'));

-- Insertion des ingrédients
INSERT INTO ingredient (nom) VALUES ('Ail');
INSERT INTO ingredient (nom) VALUES ('Ananas');
INSERT INTO ingredient (nom) VALUES ('Artichaut');
INSERT INTO ingredient (nom) VALUES ('Bacon');
INSERT INTO ingredient (nom) VALUES ('Base Tomate');
INSERT INTO ingredient (nom) VALUES ('Base crème');
INSERT INTO ingredient (nom) VALUES ('Champignon');
INSERT INTO ingredient (nom) VALUES ('Chevre');
INSERT INTO ingredient (nom) VALUES ('Cresson');
INSERT INTO ingredient (nom) VALUES ('Emmental');
INSERT INTO ingredient (nom) VALUES ('Gorgonzola');
INSERT INTO ingredient (nom) VALUES ('Jambon cuit');
INSERT INTO ingredient (nom) VALUES ('Jambon fumé');
INSERT INTO ingredient (nom) VALUES ('Oeuf');
INSERT INTO ingredient (nom) VALUES ('Oignon');
INSERT INTO ingredient (nom) VALUES ('Olive noire');
INSERT INTO ingredient (nom) VALUES ('Olive verte');
INSERT INTO ingredient (nom) VALUES ('Parmesan');
INSERT INTO ingredient (nom) VALUES ('Piment');
INSERT INTO ingredient (nom) VALUES ('Poivre');
INSERT INTO ingredient (nom) VALUES ('Pomme de terre');
INSERT INTO ingredient (nom) VALUES ('Raclette');
INSERT INTO ingredient (nom) VALUES ('Salami');
INSERT INTO ingredient (nom) VALUES ('Tomate cerise');
INSERT INTO ingredient (nom) VALUES ('Mozarella');

-- Insertion des focaccias
INSERT INTO focaccia (nom, prix) VALUES ('Mozaccia', 9.8);
INSERT INTO focaccia (nom, prix) VALUES ('Gorgonzollaccia', 10.8);
INSERT INTO focaccia (nom, prix) VALUES ('Raclaccia', 8.9);
INSERT INTO focaccia (nom, prix) VALUES ('Emmentalaccia', 9.8);
INSERT INTO focaccia (nom, prix) VALUES ('Tradizione', 8.9);
INSERT INTO focaccia (nom, prix) VALUES ('Hawaienne', 11.2);
INSERT INTO focaccia (nom, prix) VALUES ('Américaine', 10.8);
INSERT INTO focaccia (nom, prix) VALUES ('Paysanne', 12.8);

-- Insertion des relations focaccia-ingredient
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 200 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Base Tomate';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Mozarella';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Cresson';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 80 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Jambon fumé';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 2 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Ail';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Artichaut';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 40 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Champignon';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Parmesan';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 1 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Poivre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Mozaccia' AND i.nom = 'Olive noire';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 200 FROM focaccia f, ingredient i WHERE f.nom = 'Gorgonzollaccia' AND i.nom = 'Base Tomate';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Gorgonzollaccia' AND i.nom = 'Gorgonzola';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Gorgonzollaccia' AND i.nom = 'Cresson';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 2 FROM focaccia f, ingredient i WHERE f.nom = 'Gorgonzollaccia' AND i.nom = 'Ail';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 40 FROM focaccia f, ingredient i WHERE f.nom = 'Gorgonzollaccia' AND i.nom = 'Champignon';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Gorgonzollaccia' AND i.nom = 'Parmesan';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 1 FROM focaccia f, ingredient i WHERE f.nom = 'Gorgonzollaccia' AND i.nom = 'Poivre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Gorgonzollaccia' AND i.nom = 'Olive noire';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 200 FROM focaccia f, ingredient i WHERE f.nom = 'Raclaccia' AND i.nom = 'Base Tomate';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Raclaccia' AND i.nom = 'Raclette';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Raclaccia' AND i.nom = 'Cresson';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 2 FROM focaccia f, ingredient i WHERE f.nom = 'Raclaccia' AND i.nom = 'Ail';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 40 FROM focaccia f, ingredient i WHERE f.nom = 'Raclaccia' AND i.nom = 'Champignon';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Raclaccia' AND i.nom = 'Parmesan';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 1 FROM focaccia f, ingredient i WHERE f.nom = 'Raclaccia' AND i.nom = 'Poivre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 200 FROM focaccia f, ingredient i WHERE f.nom = 'Emmentalaccia' AND i.nom = 'Base crème';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Emmentalaccia' AND i.nom = 'Emmental';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Emmentalaccia' AND i.nom = 'Cresson';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 40 FROM focaccia f, ingredient i WHERE f.nom = 'Emmentalaccia' AND i.nom = 'Champignon';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Emmentalaccia' AND i.nom = 'Parmesan';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 1 FROM focaccia f, ingredient i WHERE f.nom = 'Emmentalaccia' AND i.nom = 'Poivre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Emmentalaccia' AND i.nom = 'Oignon';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 200 FROM focaccia f, ingredient i WHERE f.nom = 'Tradizione' AND i.nom = 'Base Tomate';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Tradizione' AND i.nom = 'Mozarella';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Tradizione' AND i.nom = 'Cresson';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 80 FROM focaccia f, ingredient i WHERE f.nom = 'Tradizione' AND i.nom = 'Jambon cuit';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 80 FROM focaccia f, ingredient i WHERE f.nom = 'Tradizione' AND i.nom = 'Champignon';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Tradizione' AND i.nom = 'Parmesan';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 1 FROM focaccia f, ingredient i WHERE f.nom = 'Tradizione' AND i.nom = 'Poivre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 10 FROM focaccia f, ingredient i WHERE f.nom = 'Tradizione' AND i.nom = 'Olive noire';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 10 FROM focaccia f, ingredient i WHERE f.nom = 'Tradizione' AND i.nom = 'Olive verte';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 200 FROM focaccia f, ingredient i WHERE f.nom = 'Hawaienne' AND i.nom = 'Base Tomate';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Hawaienne' AND i.nom = 'Mozarella';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Hawaienne' AND i.nom = 'Cresson';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 80 FROM focaccia f, ingredient i WHERE f.nom = 'Hawaienne' AND i.nom = 'Bacon';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 40 FROM focaccia f, ingredient i WHERE f.nom = 'Hawaienne' AND i.nom = 'Ananas';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 2 FROM focaccia f, ingredient i WHERE f.nom = 'Hawaienne' AND i.nom = 'Piment';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Hawaienne' AND i.nom = 'Parmesan';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 1 FROM focaccia f, ingredient i WHERE f.nom = 'Hawaienne' AND i.nom = 'Poivre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Hawaienne' AND i.nom = 'Olive noire';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 200 FROM focaccia f, ingredient i WHERE f.nom = 'Américaine' AND i.nom = 'Base Tomate';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Américaine' AND i.nom = 'Mozarella';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Américaine' AND i.nom = 'Cresson';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 80 FROM focaccia f, ingredient i WHERE f.nom = 'Américaine' AND i.nom = 'Bacon';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 40 FROM focaccia f, ingredient i WHERE f.nom = 'Américaine' AND i.nom = 'Pomme de terre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Américaine' AND i.nom = 'Parmesan';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 1 FROM focaccia f, ingredient i WHERE f.nom = 'Américaine' AND i.nom = 'Poivre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Américaine' AND i.nom = 'Olive noire';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 200 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Base crème';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Chevre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Cresson';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 80 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Pomme de terre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 80 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Jambon fumé';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 2 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Ail';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Artichaut';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 40 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Champignon';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Parmesan';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 1 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Poivre';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 20 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Olive noire';
INSERT INTO comprend (id_focaccia, id_ingredient, quantite) SELECT f.id_focaccia, i.id_ingredient, 50 FROM focaccia f, ingredient i WHERE f.nom = 'Paysanne' AND i.nom = 'Oeuf';
